#!/bin/bash
set -e

echo "=== Building Resource Tracker App ==="

# 1. Setup build directories
echo "Creating build directory structure..."
mkdir -p build/"Resource Tracker.app"/Contents/MacOS
mkdir -p build/"Resource Tracker.app"/Contents/Resources

# 2. Compile the asset catalog (app icon + menu bar glyph) exactly as Xcode does.
#    The artwork itself is generated by scripts/render_icon.swift.
echo "Compiling asset catalog..."
xcrun actool ResourceTracker/Assets.xcassets \
    --compile build/"Resource Tracker.app"/Contents/Resources \
    --platform macosx --minimum-deployment-target 26.0 \
    --app-icon AppIcon \
    --output-partial-info-plist build/actool-info.plist > /dev/null

# 3. Copy Info.plist config
echo "Copying Info.plist..."
cp Info.plist build/"Resource Tracker.app"/Contents/Info.plist

# 4. Compile Swift application
echo "Compiling Swift source files..."
SDK_PATH=$(xcrun --show-sdk-path)
swiftc -sdk "$SDK_PATH" -target arm64-apple-macos27.0 -O \
    -o build/"Resource Tracker.app"/Contents/MacOS/"Resource Tracker" \
    src/*.swift

echo "=== Build Completed Successfully ==="
echo "You can run the application using: open build/\"Resource Tracker.app\""
